name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
          path: "ui"
    - name: Install dependencies
      run: lein deps
      working-directory: "./ui"
    - name: Yarn dependencies
      run: yarn install
      working-directory: "./ui"
    - name: Build Prod 
      run: lein with-profile prod run -m shadow.cljs.devtools.cli release app --config-merge '{:closure-defines {alexandria.config/baseurl "https://alexandria-api-4josd7vm2q-ue.a.run.app"}}'
      working-directory: "./ui"
    - name: Authenticate into Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
         version: '270.0.0'
         service_account_email: ${{ secrets.GCP_SA_EMAIL }}
         service_account_key: ${{ secrets.GCLOUD_AUTH }} 
    - name: Sync with GCP
      run: "gsutil -m rsync -R ./ui/resources/public gs://read.jholmestech.com"
