name: API

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Check out code into the Go module directory
       uses: actions/checkout@v1
       with:
          path: "cover-gen"
          
     - name: Authenticate into Google Cloud Platform
       uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
       with:
         version: '270.0.0'
         service_account_email: ${{ secrets.GCP_SA_EMAIL }}
         service_account_key: ${{ secrets.GCLOUD_AUTH }} 
  
     - name: Build the Docker image
       run: docker build . --file cover-gen/Dockerfile --tag us.gcr.io/${{ secrets.GCLOUD_PROJECT }}/alexandria-cover-gen:$(git rev-parse --short HEAD)

     - name: Configure Docker to use Google Cloud Platform
       run: "gcloud auth configure-docker --quiet"

     - name: Push image to Google Cloud Container Registry
       run: "docker push us.gcr.io/${{ secrets.GCLOUD_PROJECT }}/alexandria-cover-gen:$(git rev-parse --short HEAD)"
        
     - name: Install beta commands and deploy on cloud run
       run: "gcloud components install beta --quiet && gcloud beta run deploy alexandria-cover-gen --quiet --image us.gcr.io/${{ secrets.GCLOUD_PROJECT }}/alexandria-cover-gen:$(git rev-parse --short HEAD) --project ${{ secrets.GCLOUD_PROJECT }} --region us-east1 --platform managed --update-env-vars SITE_BUCKET_HOST=\"gs://read.jholmestech.com\",BOOK_BUCKET_HOST=${{ secrets.BUCKET_HOST}},ACCESS_ID=${{ secrets.ACCESS_ID }},ACCESS_KEY=\"${{ secrets.ACCESS_KEY }}\""
