name: UI

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
          path: "ui"
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Elm App
      run: npm install -g create-elm-app
    - name: Npm dependencies
      run: npm install -g elm@latest-0.19.1
    - name: Build Prod
      run: elm-app build
      working-directory: "./ui"
    - name: Authenticate into Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
         version: '270.0.0'
         service_account_email: ${{ secrets.GCP_SA_EMAIL }}
         service_account_key: ${{ secrets.GCLOUD_AUTH }}
    - name: Sync with GCP
      run: "gsutil -m rsync -R ./ui/build gs://read.jholmestech.com"
